
CREATE TABLE produit (
    id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	p_name VARCHAR(256),
    price INT NOT NULL,
    p_image VARCHAR(256) NOT NULL
)
CHARACTER SET 'utf8'
ENGINE=INNODB;

CREATE TABLE commande (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    player_id INT UNSIGNED NOT NULL,
    produit_id INT UNSIGNED NOT NULL,
    price INT NOT NULL
)
CHARACTER SET 'utf8'
ENGINE=INNODB;

ALTER TABLE commande
ADD CONSTRAINT fk_commande_produit FOREIGN KEY (produit_id) REFERENCES produit(id) ON DELETE CASCADE;

ALTER TABLE commande
ADD CONSTRAINT fk_commande_player FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE;
